steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cdb-mkt-db/pubsub-to-streak-image:$COMMIT_SHA', '.' ]
  dir: 'test-form/pubsub-to-streak'
  secretEnv: ['API_KEY']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cdb-mkt-db/pubsub-to-streak-image:$COMMIT_SHA']
  dir: 'test-form/pubsub-to-streak'
  secretEnv: ['API_KEY']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'pubsub-to-streak'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cdb-mkt-db/pubsub-to-streak-image:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--set-secrets'
    - 'API_KEY=projects/13410613811/secrets/streak_api_token:latest'
    - '--service-account'
    - 'marketing-bd-379302@appspot.gserviceaccount.com'
  dir: 'test-form/pubsub-to-streak'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cdb-mkt-db/pubsub-to-streak-image:$COMMIT_SHA'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/streak_api_token/versions/latest
    env: 'API_KEY'
