steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/webhook-to-pubsub/webhook-to-pubsub-image:$COMMIT_SHA', '.' ]
  dir: 'test-form/webhook-to-pubsub'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/webhook-to-pubsub/webhook-to-pubsub-image:$COMMIT_SHA']
  dir: 'test-form/webhook-to-pubsub'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'webhook-to-pubsub'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/webhook-to-pubsub/webhook-to-pubsub-image:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--allow-unauthenticated'
  dir: 'test-form/webhook-to-pubsub'
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/webhook-to-pubsub/webhook-to-pubsub-image:$COMMIT_SHA'
